/* The following code was generated by JFlex 1.7.0 */

package Analizadores;
import java_cup.runtime.*;
import java.util.LinkedList;

//directrices

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>lexico.jflex</tt>
 */
public class Analizador_Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0, 48,  6,  8,  7,  7,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
    48,  0,  4,  0,  0,  0,  0,  9, 31, 32, 11, 26, 37,  5,  0, 10, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0, 36,  0,  0, 44, 35, 
     0, 20, 22, 19, 21, 16, 42, 39, 45, 29, 47,  2, 23, 15, 12, 18, 
    27, 46, 17, 41, 25, 30, 43,  2,  2, 38,  2,  0,  0,  0,  0,  3, 
     0, 20, 22, 19, 21, 16, 42, 39, 45, 29, 47,  2, 23, 15, 12, 18, 
    27, 46, 17, 41, 25, 30, 43,  2,  2, 38,  2,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  8,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0, 24,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 14,  0,  0,  0,  0, 34, 
     0,  0, 33, 13,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0, 33, 13,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\1\1\3\1\4\1\1\1\5"+
    "\1\6\12\1\1\7\2\1\1\10\1\11\1\1\1\12"+
    "\1\13\1\14\3\1\3\0\1\15\1\16\16\0\1\17"+
    "\12\0\1\20\1\0\1\21\3\0\1\22\1\23\1\24"+
    "\1\25\2\0\1\26\17\0\1\27\11\0\1\30\3\0"+
    "\1\31\14\0\1\32\1\0\1\33\6\0\1\34\11\0"+
    "\1\35\2\0\1\36\23\0\1\37\5\0\1\40\1\41"+
    "\2\0\1\42\1\43\14\0\1\44\4\0\1\45\6\0"+
    "\1\46\3\0\1\47\10\0\1\50\5\0\1\51\11\0"+
    "\1\52\3\0\1\53\1\54\1\0\1\55\1\56\1\57"+
    "\6\0\1\60\1\61\1\62\2\0\1\63\10\0\1\64"+
    "\1\65\5\0\1\66\1\0\1\67\10\0\1\70\11\0"+
    "\1\71\1\0\1\72\2\0\1\73\4\0\1\74\1\75"+
    "\1\76\4\0\1\77\3\0\1\100\1\101\1\0\1\102";

  private static int [] zzUnpackAction() {
    int [] result = new int[307];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\142\0\223\0\304\0\365\0\61\0\u0126"+
    "\0\u0157\0\61\0\u0188\0\u01b9\0\u01ea\0\u021b\0\u024c\0\u027d"+
    "\0\u02ae\0\u02df\0\u0310\0\u0341\0\61\0\u0372\0\u03a3\0\61"+
    "\0\61\0\u03d4\0\61\0\61\0\61\0\u0405\0\u0436\0\u0467"+
    "\0\u0498\0\u04c9\0\304\0\61\0\61\0\u04fa\0\u052b\0\u055c"+
    "\0\u058d\0\u05be\0\u05ef\0\u0620\0\u0651\0\u0682\0\u06b3\0\u06e4"+
    "\0\u0715\0\u0746\0\u0777\0\61\0\u07a8\0\u07d9\0\u080a\0\u083b"+
    "\0\u086c\0\u089d\0\u08ce\0\u08ff\0\u0930\0\u0961\0\61\0\u0992"+
    "\0\61\0\u09c3\0\u09f4\0\u0a25\0\u0498\0\61\0\61\0\u052b"+
    "\0\u0a56\0\u0a87\0\61\0\u0ab8\0\u0ae9\0\u0b1a\0\u0b4b\0\u0b7c"+
    "\0\u0bad\0\u0bde\0\u0c0f\0\u0c40\0\u0c71\0\u0ca2\0\u0cd3\0\u0d04"+
    "\0\u0d35\0\u0d66\0\61\0\u0d97\0\u0dc8\0\u0df9\0\u0e2a\0\u0e5b"+
    "\0\u0e8c\0\u0ebd\0\u0eee\0\u0f1f\0\u0f50\0\u0f81\0\u0fb2\0\u0fe3"+
    "\0\u055c\0\u1014\0\u1045\0\u1076\0\u10a7\0\u10d8\0\u1109\0\u113a"+
    "\0\u116b\0\u119c\0\u11cd\0\u11fe\0\u122f\0\61\0\u1260\0\61"+
    "\0\u1291\0\u12c2\0\u12f3\0\u1324\0\u1355\0\u1386\0\61\0\u13b7"+
    "\0\u13e8\0\u1419\0\u144a\0\u147b\0\u14ac\0\u14dd\0\u150e\0\u153f"+
    "\0\u1570\0\u15a1\0\u15d2\0\u1603\0\u1634\0\u1665\0\u1696\0\u16c7"+
    "\0\u16f8\0\u1729\0\u175a\0\u178b\0\u17bc\0\u17ed\0\u181e\0\u184f"+
    "\0\u1880\0\u18b1\0\u18e2\0\u1913\0\u1944\0\u1975\0\u19a6\0\61"+
    "\0\u19d7\0\u1a08\0\u1a39\0\u1a6a\0\u1a9b\0\61\0\u1acc\0\u1afd"+
    "\0\u1b2e\0\61\0\61\0\u1b5f\0\u1b90\0\u1bc1\0\u1bf2\0\u1c23"+
    "\0\u1c54\0\u1c85\0\u1cb6\0\u1ce7\0\u1d18\0\u1d49\0\u1d7a\0\61"+
    "\0\u1dab\0\u1ddc\0\u1e0d\0\u1e3e\0\61\0\u1e6f\0\u1ea0\0\u1ed1"+
    "\0\u1f02\0\u1f33\0\u1f64\0\61\0\u1f95\0\u1fc6\0\u1ff7\0\61"+
    "\0\u2028\0\u2059\0\u208a\0\u20bb\0\u20ec\0\u211d\0\u214e\0\u217f"+
    "\0\61\0\u21b0\0\u21e1\0\u2212\0\u2243\0\u2274\0\61\0\u22a5"+
    "\0\u22d6\0\u2307\0\u2338\0\u2369\0\u239a\0\u23cb\0\u23fc\0\u242d"+
    "\0\61\0\u245e\0\u248f\0\u24c0\0\61\0\61\0\u24f1\0\61"+
    "\0\61\0\61\0\u2522\0\u2553\0\u2584\0\u25b5\0\u25e6\0\u2617"+
    "\0\61\0\61\0\u2648\0\u2679\0\u26aa\0\61\0\u26db\0\u270c"+
    "\0\u273d\0\u276e\0\u279f\0\u27d0\0\u2801\0\u2832\0\61\0\61"+
    "\0\u2863\0\u2894\0\u28c5\0\u28f6\0\u2927\0\61\0\u2958\0\61"+
    "\0\u2989\0\u29ba\0\u29eb\0\u2a1c\0\u2a4d\0\u2a7e\0\u2aaf\0\u2ae0"+
    "\0\61\0\u2b11\0\u2b42\0\u2b73\0\u2ba4\0\u2bd5\0\u2c06\0\u2c37"+
    "\0\u2c68\0\u2c99\0\61\0\u2cca\0\61\0\u2cfb\0\u2d2c\0\61"+
    "\0\u2d5d\0\u2d8e\0\u2dbf\0\u2df0\0\61\0\61\0\61\0\u2e21"+
    "\0\u2e52\0\u2e83\0\u2eb4\0\61\0\u2ee5\0\u2f16\0\u2f47\0\61"+
    "\0\61\0\u2f78\0\61";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[307];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\2\1\4\1\5\1\6\2\7\1\0"+
    "\1\10\1\11\1\12\1\13\2\2\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\2\2\1\25"+
    "\1\26\2\27\1\2\1\30\1\31\1\32\1\2\1\33"+
    "\1\34\1\35\2\2\2\36\1\37\2\2\1\40\2\2"+
    "\1\7\61\0\1\41\1\3\4\41\3\0\50\41\2\0"+
    "\1\42\11\0\1\42\2\0\11\42\1\0\1\42\1\0"+
    "\1\42\1\0\2\42\7\0\2\42\1\0\3\42\1\0"+
    "\3\42\1\0\4\43\1\44\54\43\1\0\1\3\52\0"+
    "\1\45\6\0\1\46\11\0\1\46\2\0\11\46\1\0"+
    "\1\46\1\0\1\46\1\0\2\46\7\0\2\46\1\0"+
    "\3\46\1\0\3\46\13\0\1\47\1\50\62\0\1\51"+
    "\4\0\1\52\56\0\1\53\1\0\1\54\1\0\1\55"+
    "\7\0\2\56\37\0\1\57\33\0\2\60\5\0\1\61"+
    "\21\0\1\62\43\0\1\63\15\0\1\64\61\0\1\65"+
    "\1\0\1\66\50\0\1\67\64\0\1\70\62\0\1\71"+
    "\72\0\2\72\45\0\1\73\1\0\1\74\50\0\1\75"+
    "\2\0\1\76\103\0\1\77\36\0\1\100\13\0\2\101"+
    "\57\0\2\102\1\103\46\0\1\104\35\0\1\105\60\0"+
    "\2\42\1\106\10\0\1\42\2\0\11\42\1\0\1\42"+
    "\1\0\1\42\1\0\2\42\7\0\2\42\1\0\3\42"+
    "\1\0\3\42\12\0\1\107\47\0\4\47\1\0\1\47"+
    "\1\110\52\47\4\50\1\0\6\50\1\111\45\50\16\0"+
    "\1\112\73\0\1\113\43\0\1\114\14\0\1\115\54\0"+
    "\1\116\101\0\1\117\32\0\1\120\71\0\1\121\32\0"+
    "\1\122\75\0\1\123\71\0\1\124\1\0\1\125\75\0"+
    "\2\126\23\0\1\127\2\0\1\130\62\0\1\131\3\0"+
    "\1\132\60\0\1\133\36\0\1\134\77\0\1\135\106\0"+
    "\2\136\40\0\1\137\50\0\1\140\73\0\2\141\11\0"+
    "\1\142\44\0\1\143\74\0\1\144\25\0\1\145\60\0"+
    "\1\146\67\0\1\147\24\0\2\150\7\0\4\50\1\0"+
    "\5\50\1\151\1\111\45\50\17\0\1\152\63\0\1\153"+
    "\60\0\1\154\74\0\1\155\44\0\1\156\52\0\1\157"+
    "\66\0\1\160\63\0\1\161\6\0\2\162\46\0\1\163"+
    "\57\0\1\164\56\0\1\165\74\0\2\166\26\0\1\167"+
    "\77\0\1\170\53\0\1\171\63\0\1\172\67\0\1\173"+
    "\60\0\1\174\62\0\1\175\47\0\1\176\64\0\1\177"+
    "\57\0\1\200\56\0\1\201\60\0\1\202\75\0\1\203"+
    "\25\0\1\204\100\0\1\205\55\0\1\206\71\0\1\207"+
    "\47\0\1\210\61\0\1\211\64\0\1\212\62\0\1\213"+
    "\52\0\1\214\70\0\1\215\43\0\1\216\100\0\2\217"+
    "\72\0\1\220\47\0\1\221\43\0\1\222\70\0\1\223"+
    "\62\0\1\224\2\225\15\0\1\226\35\0\1\227\44\0"+
    "\1\230\66\0\1\231\56\0\1\232\64\0\1\233\50\0"+
    "\1\234\100\0\2\235\43\0\1\236\74\0\2\237\37\0"+
    "\1\240\63\0\1\241\13\0\1\242\14\0\2\243\1\244"+
    "\42\0\2\245\44\0\1\246\63\0\1\247\55\0\1\250"+
    "\42\0\1\251\77\0\1\252\60\0\1\253\41\0\1\254"+
    "\76\0\1\255\62\0\1\256\107\0\1\257\44\0\1\260"+
    "\53\0\1\261\43\0\1\262\100\0\2\263\47\0\1\264"+
    "\50\0\1\265\70\0\1\266\57\0\1\267\61\0\1\270"+
    "\37\0\1\271\101\0\1\272\37\0\1\273\100\0\1\274"+
    "\57\0\1\275\106\0\2\276\26\0\1\277\61\0\1\300"+
    "\13\0\2\301\47\0\1\302\54\0\1\303\13\0\2\304"+
    "\61\0\1\305\44\0\1\306\41\0\1\307\77\0\1\310"+
    "\60\0\1\311\60\0\1\312\62\0\1\313\54\0\1\314"+
    "\60\0\1\315\64\0\1\316\60\0\1\317\60\0\1\320"+
    "\55\0\1\321\60\0\1\322\62\0\1\323\64\0\1\324"+
    "\62\0\1\325\52\0\1\326\51\0\1\327\71\0\1\330"+
    "\67\0\2\331\47\0\1\332\70\0\2\333\54\0\1\334"+
    "\47\0\1\335\61\0\1\336\106\0\1\337\25\0\1\340"+
    "\60\0\1\341\122\0\1\342\5\0\1\343\60\0\1\344"+
    "\125\0\2\345\57\0\2\346\30\0\1\347\66\0\1\350"+
    "\52\0\1\351\60\0\1\352\63\0\1\353\55\0\1\354"+
    "\61\0\1\355\56\0\1\356\62\0\1\357\56\0\1\360"+
    "\64\0\1\361\55\0\1\362\60\0\1\363\61\0\1\364"+
    "\52\0\1\365\70\0\1\366\72\0\1\367\45\0\1\370"+
    "\73\0\1\371\56\0\2\372\57\0\2\373\43\0\1\374"+
    "\57\0\1\375\61\0\1\376\61\0\1\377\60\0\1\u0100"+
    "\53\0\1\u0101\47\0\1\u0102\60\0\1\u0103\102\0\1\u0104"+
    "\64\0\1\u0105\43\0\1\u0106\100\0\2\u0107\43\0\1\u0108"+
    "\107\0\1\u0109\60\0\1\u010a\25\0\1\u010b\64\0\1\u010c"+
    "\57\0\1\u010d\72\0\1\u010e\43\0\1\u010f\60\0\1\u0110"+
    "\66\0\1\u0111\57\0\1\u0112\61\0\1\u0113\74\0\1\u0114"+
    "\60\0\1\u0115\53\0\1\u0116\60\0\1\u0117\47\0\1\u0118"+
    "\61\0\1\u0119\61\0\1\u011a\65\0\1\u011b\55\0\1\u011c"+
    "\50\0\1\u011d\70\0\1\u011e\60\0\1\u011f\54\0\1\u0120"+
    "\61\0\1\u0121\53\0\1\u0122\70\0\1\u0123\53\0\1\u0124"+
    "\111\0\2\u0125\36\0\1\u0126\60\0\1\u0127\53\0\1\u0128"+
    "\67\0\1\u0129\50\0\1\u012a\65\0\1\u012b\102\0\2\u012c"+
    "\33\0\1\u012d\70\0\2\u012e\44\0\1\u012f\66\0\1\u0130"+
    "\53\0\1\u0131\56\0\1\u0132\110\0\2\u0133\7\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[12201];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\4\1\1\11\2\1\1\11\12\1\1\11"+
    "\2\1\2\11\1\1\3\11\3\1\3\0\2\11\16\0"+
    "\1\11\12\0\1\11\1\0\1\11\3\0\1\1\2\11"+
    "\1\1\2\0\1\11\17\0\1\11\11\0\1\1\3\0"+
    "\1\1\14\0\1\11\1\0\1\11\6\0\1\11\11\0"+
    "\1\1\2\0\1\1\23\0\1\11\5\0\1\11\1\1"+
    "\2\0\2\11\14\0\1\11\4\0\1\11\6\0\1\11"+
    "\3\0\1\11\10\0\1\11\5\0\1\11\11\0\1\11"+
    "\3\0\2\11\1\0\3\11\6\0\2\11\1\1\2\0"+
    "\1\11\10\0\2\11\5\0\1\11\1\0\1\11\10\0"+
    "\1\11\11\0\1\11\1\0\1\11\2\0\1\11\4\0"+
    "\3\11\4\0\1\11\3\0\2\11\1\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[307];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    public static LinkedList<claseErrores> TError = new LinkedList<claseErrores>();


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Analizador_Lexico(java.io.Reader in) {
    this.zzReader = in;
  }



  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(Simbolos.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.println("-> Error Léxico:"+yytext());
    System.out.println("Linea: "+ yyline + "  Columna:  "+ yycolumn);
    claseErrores datos = new claseErrores(yytext(), "Error Léxico", "Simbolo no existe en el lenguaje",yyline, yycolumn);
    TError.add(datos);
            } 
            // fall through
          case 67: break;
          case 2: 
            { System.out.println("Token:<digitoEntero> lexema:"+yytext());
                            return new Symbol(Simbolos.digitoEntero,yyline,yycolumn,yytext());
            } 
            // fall through
          case 68: break;
          case 3: 
            { System.out.println("Token:<resta> lexema:"+yytext());
                return new Symbol(Simbolos.resta,yyline,yycolumn,yytext());
            } 
            // fall through
          case 69: break;
          case 4: 
            { /*este es un comentario en java, omitirlos*/
            } 
            // fall through
          case 70: break;
          case 5: 
            { System.out.println("Token:<División> lexema:"+yytext());
                return new Symbol(Simbolos.div,yyline,yycolumn,yytext());
            } 
            // fall through
          case 71: break;
          case 6: 
            { System.out.println("Token:<multiplicación> lexema:"+yytext());
                return new Symbol(Simbolos.mult,yyline,yycolumn,yytext());
            } 
            // fall through
          case 72: break;
          case 7: 
            { System.out.println("Token:<suma> lexema:"+yytext());
                return new Symbol(Simbolos.mas,yyline,yycolumn,yytext());
            } 
            // fall through
          case 73: break;
          case 8: 
            { System.out.println("Token:<Parentesis_A> lexema:"+yytext());
                return new Symbol(Simbolos.abrir_par, yyline,yycolumn, yytext());
            } 
            // fall through
          case 74: break;
          case 9: 
            { System.out.println("Token:<Parentesis_C> lexema:"+yytext());
                return new Symbol(Simbolos.cerrar_par, yyline,yycolumn, yytext());
            } 
            // fall through
          case 75: break;
          case 10: 
            { System.out.println("Token:<interr_C> lexema:"+yytext());
                return new Symbol(Simbolos.cerrar_interr, yyline,yycolumn, yytext());
            } 
            // fall through
          case 76: break;
          case 11: 
            { System.out.println("Token:<puntoComa> lexema:"+yytext());
                return new Symbol(Simbolos.puntoComa, yyline,yycolumn, yytext());
            } 
            // fall through
          case 77: break;
          case 12: 
            { System.out.println("Token:<Coma> lexema:"+yytext());
                return new Symbol(Simbolos.Coma, yyline,yycolumn, yytext());
            } 
            // fall through
          case 78: break;
          case 13: 
            { System.out.println("Token:<Cadena> lexema:"+yytext());
                    return new Symbol(Simbolos.Cadena,yyline,yycolumn,yytext());
            } 
            // fall through
          case 79: break;
          case 14: 
            { System.out.println("Token:<Simbolo_asignacion> lexema:"+yytext());
                    return new Symbol(Simbolos.asignacion, yyline,yycolumn, yytext());
            } 
            // fall through
          case 80: break;
          case 15: 
            { System.out.println("Token:<or> lexema:"+yytext());
                    return new Symbol(Simbolos.or, yyline,yycolumn, yytext());
            } 
            // fall through
          case 81: break;
          case 16: 
            { System.out.println("Token:<interr_A> lexema:"+yytext());
                return new Symbol(Simbolos.abrir_interr, yyline,yycolumn, yytext());
            } 
            // fall through
          case 82: break;
          case 17: 
            { System.out.println("Token:<condSi> lexema:"+yytext());
                    return new Symbol(Simbolos.condSi,yyline,yycolumn, yytext());
            } 
            // fall through
          case 83: break;
          case 18: 
            { System.out.println("Token:<digitoDecimal> lexema:"+yytext());
                            return new Symbol(Simbolos.digitoDecimal,yyline,yycolumn,yytext());
            } 
            // fall through
          case 84: break;
          case 19: 
            { System.out.println("Token:<id> lexema:"+yytext());
                    return new Symbol(Simbolos.id, yyline,yycolumn, yytext());
            } 
            // fall through
          case 85: break;
          case 20: 
            { System.out.println("Token:<caracter> lexema:"+yytext());
                        return new Symbol(Simbolos.caracter,yyline,yycolumn,yytext());
            } 
            // fall through
          case 86: break;
          case 21: 
            { System.out.println("Token:<comentario> lexema:"+yytext());
                            return new Symbol(Simbolos.comentario, yyline,yycolumn, yytext());
            } 
            // fall through
          case 87: break;
          case 22: 
            { System.out.println("Token:<not> lexema:"+yytext());
                    return new Symbol(Simbolos.not, yyline,yycolumn, yytext());
            } 
            // fall through
          case 88: break;
          case 23: 
            { System.out.println("Token:<and> lexema:"+yytext());
                    return new Symbol(Simbolos.and, yyline,yycolumn, yytext());
            } 
            // fall through
          case 89: break;
          case 24: 
            { System.out.println("Token Reservada:<fin> lexema:"+yytext());
                    return new Symbol(Simbolos.fin, yyline,yycolumn, yytext());
            } 
            // fall through
          case 90: break;
          case 25: 
            { System.out.println("Token:<comentario> lexema:"+yytext());
                            return new Symbol(Simbolos.comentario,yyline,yycolumn, yytext());
            } 
            // fall through
          case 91: break;
          case 26: 
            { System.out.println("Token:<OSi> lexema:"+yytext());
                    return new Symbol(Simbolos.OSi, yyline,yycolumn, yytext());
            } 
            // fall through
          case 92: break;
          case 27: 
            { System.out.println("Token reservada:<como> lexema:"+yytext());
                    return new Symbol(Simbolos.Rcomo, yyline,yycolumn, yytext());
            } 
            // fall through
          case 93: break;
          case 28: 
            { System.out.println("Token:<para> lexema:"+yytext());
                    return new Symbol(Simbolos.para, yyline,yycolumn, yytext());
            } 
            // fall through
          case 94: break;
          case 29: 
            { System.out.println("Token:<menor> lexema:"+yytext());
                    return new Symbol(Simbolos.menor, yyline,yycolumn, yytext());
            } 
            // fall through
          case 95: break;
          case 30: 
            { System.out.println("Token:<mayor> lexema:"+yytext());
                    return new Symbol(Simbolos.mayor, yyline,yycolumn, yytext());
            } 
            // fall through
          case 96: break;
          case 31: 
            { System.out.println("Token:<segun> lexema:"+yytext());
                    return new Symbol(Simbolos.segun, yyline,yycolumn, yytext());
            } 
            // fall through
          case 97: break;
          case 32: 
            { System.out.println("Token:<hacer> lexema:"+yytext());
                    return new Symbol(Simbolos.hacer, yyline,yycolumn, yytext());
            } 
            // fall through
          case 98: break;
          case 33: 
            { System.out.println("Token:<hasta> lexema:"+yytext());
                    return new Symbol(Simbolos.hasta, yyline,yycolumn, yytext());
            } 
            // fall through
          case 99: break;
          case 34: 
            { System.out.println("Token:<metodo> lexema:"+yytext());
                        return new Symbol(Simbolos.metodo, yyline,yycolumn, yytext());
            } 
            // fall through
          case 100: break;
          case 35: 
            { System.out.println("Token Reservada:<modulo> lexema:"+yytext());
                    return new Symbol(Simbolos.Rmod,yyline,yycolumn,yytext());
            } 
            // fall through
          case 101: break;
          case 36: 
            { System.out.println("Token Reservada:<Cadena> lexema:"+yytext());
                    return new Symbol(Simbolos.Rcadena,yyline,yycolumn,yytext());
            } 
            // fall through
          case 102: break;
          case 37: 
            { System.out.println("Token Reservada:<inicio> lexema:"+yytext());
                        return new Symbol(Simbolos.inicio, yyline,yycolumn, yytext());
            } 
            // fall through
          case 103: break;
          case 38: 
            { System.out.println("Token:<finSi> lexema:"+yytext());
                        return new Symbol(Simbolos.finSi, yyline,yycolumn, yytext());
            } 
            // fall through
          case 104: break;
          case 39: 
            { System.out.println("Token Reservada:<Número> lexema:"+yytext());
                    return new Symbol(Simbolos.Rnumero,yyline,yycolumn,yytext());
            } 
            // fall through
          case 105: break;
          case 40: 
            { System.out.println("Token:<repetir> lexema:"+yytext());
                        return new Symbol(Simbolos.repetir,yyline,yycolumn, yytext());
            } 
            // fall through
          case 106: break;
          case 41: 
            { System.out.println("Token Reservada:<Boolean> lexema:"+yytext());
                        return new Symbol(Simbolos.Rboolean,yyline,yycolumn,yytext());
            } 
            // fall through
          case 107: break;
          case 42: 
            { System.out.println("Token:<funcion> lexema:"+yytext());
                        return new Symbol(Simbolos.funcion, yyline,yycolumn, yytext());
            } 
            // fall through
          case 108: break;
          case 43: 
            { System.out.println("Token:<mientras> lexema:"+yytext());
                        return new Symbol(Simbolos.mientras, yyline,yycolumn, yytext());
            } 
            // fall through
          case 109: break;
          case 44: 
            { System.out.println("Token:<entonces> lexema:"+yytext());
                        return new Symbol(Simbolos.entonces, yyline,yycolumn, yytext());
            } 
            // fall through
          case 110: break;
          case 45: 
            { System.out.println("Token:<igual> lexema:"+yytext());
                        return new Symbol(Simbolos.igual, yyline,yycolumn, yytext());
            } 
            // fall through
          case 111: break;
          case 46: 
            { System.out.println("Token:<ejecutar> lexema:"+yytext());
                        return new Symbol(Simbolos.ejecutar, yyline,yycolumn, yytext());
            } 
            // fall through
          case 112: break;
          case 47: 
            { System.out.println("Token:<retornar> lexema:"+yytext());
                        return new Symbol(Simbolos.retornar, yyline,yycolumn, yytext());
            } 
            // fall through
          case 113: break;
          case 48: 
            { System.out.println("Token Reservada:<potencia> lexema:"+yytext());
                        return new Symbol(Simbolos.Rpotencia,yyline,yycolumn,yytext());
            } 
            // fall through
          case 114: break;
          case 49: 
            { System.out.println("Token Reservada:<ingresar> lexema:"+yytext());
                        return new Symbol(Simbolos.Ringresar,yyline,yycolumn, yytext());
            } 
            // fall through
          case 115: break;
          case 50: 
            { System.out.println("Token:<imprimir> lexema:"+yytext());
                        return new Symbol(Simbolos.imprimir, yyline,yycolumn, yytext());
            } 
            // fall through
          case 116: break;
          case 51: 
            { System.out.println("Token:<finPara> lexema:"+yytext());
                        return new Symbol(Simbolos.finPara,yyline,yycolumn, yytext());
            } 
            // fall through
          case 117: break;
          case 52: 
            { System.out.println("Token Reservada:<con_valor> lexema:"+yytext());
                        return new Symbol(Simbolos.RCon_valor,yyline,yycolumn, yytext());
            } 
            // fall through
          case 118: break;
          case 53: 
            { System.out.println("Token Reservada:<Carácter> lexema:"+yytext());
                        return new Symbol(Simbolos.Rcaracter,yyline,yycolumn,yytext());
            } 
            // fall through
          case 119: break;
          case 54: 
            { System.out.println("Token:<finSegun> lexema:"+yytext());
                        return new Symbol(Simbolos.finSegun, yyline,yycolumn, yytext());
            } 
            // fall through
          case 120: break;
          case 55: 
            { System.out.println("Token:<hasta_que> lexema:"+yytext());
                        return new Symbol(Simbolos.hastaQue, yyline,yycolumn, yytext());
            } 
            // fall through
          case 121: break;
          case 56: 
            { System.out.println("Token:<Finmetodo> lexema:"+yytext());
                            return new Symbol(Simbolos.Finmetodo, yyline,yycolumn, yytext());
            } 
            // fall through
          case 122: break;
          case 57: 
            { System.out.println("Token:<imprimir_nl> lexema:"+yytext());
                            return new Symbol(Simbolos.imprimir_nl, yyline,yycolumn,yytext());
            } 
            // fall through
          case 123: break;
          case 58: 
            { System.out.println("Token:<Finfuncion> lexema:"+yytext());
                            return new Symbol(Simbolos.Finfuncion,yyline,yycolumn, yytext());
            } 
            // fall through
          case 124: break;
          case 59: 
            { System.out.println("Token:<diferente> lexema:"+yytext());
                            return new Symbol(Simbolos.diferente,yyline,yycolumn, yytext());
            } 
            // fall through
          case 125: break;
          case 60: 
            { System.out.println("Token:<fin_mientras> lexema:"+yytext());
                            return new Symbol(Simbolos.finMientras, yyline,yycolumn, yytext());
            } 
            // fall through
          case 126: break;
          case 61: 
            { System.out.println("Token:<menorIgual> lexema:"+yytext());
                            return new Symbol(Simbolos.menorIgual, yyline,yycolumn, yytext());
            } 
            // fall through
          case 127: break;
          case 62: 
            { System.out.println("Token:<mayorIgual> lexema:"+yytext());
                            return new Symbol(Simbolos.mayorIgual, yyline,yycolumn, yytext());
            } 
            // fall through
          case 128: break;
          case 63: 
            { System.out.println("Token:<con_parametros> lexema:"+yytext());
                                return new Symbol(Simbolos.con_parametros,yyline,yycolumn, yytext());
            } 
            // fall through
          case 129: break;
          case 64: 
            { System.out.println("Token:<incremento> lexema:"+yytext());
                                return new Symbol(Simbolos.incremento, yyline,yycolumn, yytext());
            } 
            // fall through
          case 130: break;
          case 65: 
            { System.out.println("Token:<contrario> lexema:"+yytext());
                                return new Symbol(Simbolos.contrario,yyline,yycolumn, yytext());
            } 
            // fall through
          case 131: break;
          case 66: 
            { System.out.println("Token:<listaN> lexema:"+yytext());
                                return new Symbol(Simbolos.listaN,yyline,yycolumn, yytext());
            } 
            // fall through
          case 132: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
