
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int Coma = 26;
  public static final int finMientras = 56;
  public static final int resta = 16;
  public static final int imprimir = 66;
  public static final int con_parametros = 62;
  public static final int condSi = 43;
  public static final int Rfalse = 8;
  public static final int RCon_valor = 41;
  public static final int hasta = 52;
  public static final int hastaQue = 58;
  public static final int Rcadena = 12;
  public static final int entonces = 49;
  public static final int igual = 31;
  public static final int Rcaracter = 14;
  public static final int finSi = 45;
  public static final int digitoEntero = 3;
  public static final int inicio = 36;
  public static final int caracter = 5;
  public static final int repetir = 57;
  public static final int menorIgual = 30;
  public static final int mientras = 55;
  public static final int abrir_cor = 9;
  public static final int Rboolean = 13;
  public static final int citr = 24;
  public static final int digitoDecimal = 4;
  public static final int Cadena = 2;
  public static final int abrir_par = 21;
  public static final int menor = 28;
  public static final int finSegun = 50;
  public static final int EOF = 0;
  public static final int mas = 15;
  public static final int Finfuncion = 64;
  public static final int para = 51;
  public static final int mayorIgual = 29;
  public static final int error = 1;
  public static final int mayor = 27;
  public static final int metodo = 60;
  public static final int caracterAS = 6;
  public static final int or = 33;
  public static final int Rcomo = 40;
  public static final int aitr = 23;
  public static final int Rpotencia = 19;
  public static final int funcion = 63;
  public static final int Rnumero = 11;
  public static final int OSi = 46;
  public static final int imprimir_nl = 67;
  public static final int id = 39;
  public static final int incremento = 53;
  public static final int Ringresar = 38;
  public static final int puntoComa = 25;
  public static final int finPara = 54;
  public static final int segun = 47;
  public static final int hacer = 48;
  public static final int Rtrue = 7;
  public static final int mult = 17;
  public static final int cerrar_cor = 10;
  public static final int fin = 37;
  public static final int Rmod = 20;
  public static final int diferente = 32;
  public static final int not = 35;
  public static final int and = 34;
  public static final int cerrar_par = 22;
  public static final int retornar = 59;
  public static final int Finmetodo = 61;
  public static final int div = 18;
  public static final int asignacion = 42;
  public static final int ejecutar = 65;
  public static final int contrario = 44;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Cadena",
  "digitoEntero",
  "digitoDecimal",
  "caracter",
  "caracterAS",
  "Rtrue",
  "Rfalse",
  "abrir_cor",
  "cerrar_cor",
  "Rnumero",
  "Rcadena",
  "Rboolean",
  "Rcaracter",
  "mas",
  "resta",
  "mult",
  "div",
  "Rpotencia",
  "Rmod",
  "abrir_par",
  "cerrar_par",
  "aitr",
  "citr",
  "puntoComa",
  "Coma",
  "mayor",
  "menor",
  "mayorIgual",
  "menorIgual",
  "igual",
  "diferente",
  "or",
  "and",
  "not",
  "inicio",
  "fin",
  "Ringresar",
  "id",
  "Rcomo",
  "RCon_valor",
  "asignacion",
  "condSi",
  "contrario",
  "finSi",
  "OSi",
  "segun",
  "hacer",
  "entonces",
  "finSegun",
  "para",
  "hasta",
  "incremento",
  "finPara",
  "mientras",
  "finMientras",
  "repetir",
  "hastaQue",
  "retornar",
  "metodo",
  "Finmetodo",
  "con_parametros",
  "funcion",
  "Finfuncion",
  "ejecutar",
  "imprimir",
  "imprimir_nl"
  };
}

